# Generated by Django 5.2.14 on 2026-05-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sntapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='fee_type',
            field=models.CharField(choices=[('membership', 'Членский взнос'), ('target', 'Целевой взнос'), ('other', 'Прочие взносы')], max_length=20, verbose_name='Тип взноса'),
        ),
    ]
