# Generated by Django 5.2.14 on 2026-05-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sntapp', '0002_alter_debt_fee_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-is_important', '-uploaded_at'], 'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описание документа', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='document',
            name='downloads_count',
            field=models.IntegerField(default=0, verbose_name='Количество скачиваний'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.IntegerField(default=0, editable=False, verbose_name='Размер файла (байт)'),
        ),
        migrations.AddField(
            model_name='document',
            name='is_important',
            field=models.BooleanField(default=False, help_text='Помечает документ как важный', verbose_name='Важный документ'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('charter', 'Устав СНТ'), ('protocol', 'Протокол собрания'), ('report', 'Отчет правления'), ('financial', 'Финансовые документы'), ('regulations', 'Положения и регламенты'), ('contract', 'Договоры'), ('other', 'Прочее')], default='other', max_length=20, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='preview',
            field=models.ImageField(blank=True, help_text='Миниатюра для предпросмотра документа (опционально)', null=True, upload_to='document_previews/%Y/%m/%d/', verbose_name='Превью'),
        ),
    ]
