# Generated by Django 5.2.14 on 2026-05-20 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sntapp', '0003_alter_document_options_document_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('phone', 'Телефон'), ('email', 'Email'), ('address', 'Адрес'), ('schedule', 'Режим работы'), ('social', 'Социальная сеть'), ('other', 'Другое')], max_length=20, verbose_name='Тип контакта')),
                ('value', models.CharField(max_length=300, verbose_name='Значение')),
                ('icon', models.CharField(blank=True, help_text='Font Awesome иконка (например, fas fa-phone)', max_length=50, verbose_name='Иконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
                'ordering': ['order', 'contact_type'],
            },
        ),
        migrations.CreateModel(
            name='ManagementMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('position', models.CharField(choices=[('chairman', 'Председатель'), ('deputy', 'Заместитель председателя'), ('treasurer', 'Казначей'), ('secretary', 'Секретарь'), ('member', 'Член правления'), ('auditor', 'Ревизор')], max_length=20, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='management/%Y/%m/%d/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, help_text='Краткая информация о члене правления', verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Член правления',
                'verbose_name_plural': 'Члены правления',
                'ordering': ['order', 'position'],
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('about', 'О нас'), ('management', 'Правление'), ('info', 'Информация'), ('contacts', 'Контакты')], help_text='Выберите тип страницы', max_length=20, unique=True, verbose_name='Тип страницы')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(help_text='HTML-разметка поддерживается', verbose_name='Содержание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/%Y/%m/%d/', verbose_name='Изображение страницы')),
                ('seo_title', models.CharField(blank=True, help_text='Для поисковых систем', max_length=200, verbose_name='SEO заголовок')),
                ('seo_description', models.CharField(blank=True, max_length=500, verbose_name='SEO описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статическая страница',
                'verbose_name_plural': 'Статические страницы',
                'ordering': ['order', 'page_type'],
            },
        ),
    ]
