# Generated by Django 5.2.14 on 2026-05-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sntapp', '0004_contactinfo_managementmember_staticpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lot_number',
            field=models.CharField(blank=True, help_text='Номер участка в СНТ (используется как логин)', max_length=10, null=True, unique=True, verbose_name='Номер участка'),
        ),
    ]
