# Generated by Django 5.2.14 on 2026-06-10 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sntapp', '0005_alter_user_lot_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Важное объявление', max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст объявления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('expire_at', models.DateTimeField(blank=True, help_text='После этой даты объявление скроется автоматически', null=True, verbose_name='Дата и время удаления')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Важное объявление',
                'verbose_name_plural': 'Важные объявления',
                'ordering': ['-created_at'],
            },
        ),
    ]
